name: 5- Clean logs
run-name: Clean runs logs
on:
  workflow_dispatch:
  schedule:
    - cron:  '0 0 * * 1' # every Monday

jobs:
 Cleaning:
    runs-on: ubuntu-latest

    steps:
      - uses: igorjs/gh-actions-clean-workflow@v6
        with:
          runs_older_than: 0 
          token: ${{ github.token }}
          runs_to_keep: 1