name: 2- Deploy PR to staging env

on:
  pull_request:
    branches:
    - main

concurrency: ci-${{ github.event.number }}

env:
  WEBAPP_NAME: ${{ vars.WEBAPP_NAME }}
  RESOURCE_GROUP: ${{ vars.RESOURCE_GROUP }}
  SLOT_NAME: pr-${{ github.event.number }}

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
    - name: Check out repo
      uses: actions/checkout@v4

    - name: Install .Net
      uses: actions/setup-dotnet@v4
      with:
        dotnet-version: '9.0.x'

    - name: Build app
      run: echo "put build activities here"
 
    - name: zip binaries
      run: |
        cd src
        zip -r ../my-app.zip .

    - name: Upload artifact for deployment job
      uses: actions/upload-artifact@v4
      with:
        name: my-app
        path: '${{ github.workspace }}/my-app.zip'
  
  set-up-test-env:
    name: Create test env
    runs-on: ubuntu-latest

    steps:
    - name: Log into Azure CLI with service principal
      uses: azure/login@v2
      with:
        creds: ${{ secrets.AZURE_CREDENTIALS }}

    - name: Create slot on staging site
      run: az webapp deployment slot create --resource-group $RESOURCE_GROUP  --name $WEBAPP_NAME --slot $SLOT_NAME

  deploy:
    name: Deploy to test env
    runs-on: ubuntu-latest
    needs: [build, set-up-test-env]
    environment:
      name: "PR #${{ github.event.number }}"
      url: ${{ steps.deploy-to-webapp.outputs.webapp-url }}
    permissions:
      pull-requests: write

    steps:
    - name: Download artifact from build job
      uses: actions/download-artifact@v4
      with:
        name: my-app

    - name: Log into Azure CLI with service principal
      uses: azure/login@v2
      with:
        creds: ${{ secrets.AZURE_CREDENTIALS }}
    
    - name: Deploy to slot on staging site
      uses: azure/webapps-deploy@v3
      id: deploy-to-webapp
      with: 
        app-name: ${{ env.WEBAPP_NAME }}
        slot-name:  ${{ env.SLOT_NAME }}
        package: 'my-app.zip'
        target-path: /home/site/wwwroot/public # necessary for PHP

    - name: Comment on PR with the preview link
      uses: mshick/add-pr-comment@v2
      with:
        message: |
          ## Preview link: https://${{ env.WEBAPP_NAME }}-${{env.SLOT_NAME }}.azurewebsites.net 
          
          - Your changes have been deployed to the preview site. The preview site will update as you add more commits to this branch.
          - The preview link is shareable, but will be deleted when the pull request is merged or closed.

          > *This is an automated message.*
        repo-token: ${{ secrets.GITHUB_TOKEN }}

    - name: Setup tmate session
      if: ${{ failure() }}
      uses: mxschmitt/action-tmate@v3
   