name: Deploy Infra

on:
  workflow_dispatch:

jobs:
  deployInfra:
    runs-on: ubuntu-latest
    steps:
    - name: Check out repo
      uses: actions/checkout@v4

    - uses: azure/arm-deploy@v2
      with:
        resourceGroupName: ${{ env.RESOURCE_GROUP }}
        template: ./infra/template.json
        parameters: infra/parameters.json resourceGroupName=${{ env.RESOURCE_GROUP }} name=${{ env.WEBAPP_NAME }} subscriptionId=${{ env.SUBSCRIPTION_ID }}
